https://dataexplorer.azure.com/clusters/genevaactions/databases/Production?query=H4sIAAAAAAAAA5VTTY%2FTMBC98ysGX5KglEXcYLVIq1VB5bCtmpYe0RBPU0NqR%2FakZSXEb2cSN%2F1YWK3oqfPmvefJ87is28Dk06QiSzvEko2zIclea2T8hoHSZOadbntc4NtWG4YXv2C%2FIU9AdveVzZbgww1g5dJ3b3QGaDWMrW6csXyP0rz5DecukfCTyQYpB4a6n89U3%2BrPGO%2FI8uKhITAWUlW0ZUmkSasc1Ec0tfzLTnNMQkF%2BZ0qaaJEZfujPXGMdKAHnYRnIn7eUQwwjdiPrmxGWJoxomGdUYl2rzrqH9CMtGLNO%2F9tOhp4iFochbyVsFuzcJjt%2By7Qhjzwk87J0ltHYAKoijgE9yfCE%2BhlKbQKrZ3Jj38bY0kc2EkfYG97Er%2FnnSSfKggLPWyvXdHUFnycL6GE30AN01Ah2boAyz4Zq6Z9IMmiDPhDM0Iu9bOpB8QpU2JLE7akSXtO13yuY9xWo62slFPnJ0dGANwSRe7rZyO6XLN7rQd5tXDLGwMvi7bjFJsmTO4nHY70s%2BjrLIblDi%2F4hyZ8QFotPIitcy5ujNmIr6vpfsDYa46sSt4KxMrYSu%2F6lJFl2GlN6nqfrFdEPmTN0lVvvpUqH59eRG%2B%2B%2BU8kw8yQLSAuBRbhtRDLQ8nOr%2FPLm8kMal1uZ%2F70hHXRUzmXhVt6wyC9fbX4W7h8QJeDVZAQAAA%3D%3D

cluster('genevaactions').database('Production').Audit 
| where env_time >= ago(90d) and EndpointName =~ 'Production' and ExtensionName =~ "NRP" and AuditEventType in ("Succeeded", "Failed") 
| where IsServiceIdentity =~ 'false' or UserIdentity =~ "oaas-to-nrp-acis-extension-call" 
| extend UserIdentity = iif(UserIdentity =~ "oaas-to-nrp-acis-extension-call", "OaaSServiceAgent", UserIdentity)
| where OperationName !contains "get" and OperationName !contains "read" and OperationName !contains "list"
| where IsServiceIdentity =~ 'true' or (OperationName !endswith "OaaS" and OperationName !endswith "TestRun") // JIT with operations ends with OaaS are helper operation
| parse Parameters with * "smenrpregionparam:" Region ";;" *    // parse the region
| extend RegionType = iif(Region in ('EastUS2Euap','CentralUSEuap'), 'Canary', iif(Region in ('EastUSSTG','SouthCentralUSSTG','WestUSValidation'), 'Staging', 'Prod'))
| extend StartOfWeek = startofweek(env_time)
| project PreciseTimeStamp = env_time, StartOfWeek, OperationName, Region, UserIdentity, IsServiceIdentity, IsOperationReadWrite, AuditEventType, RegionType

  